name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            extra-platforms = aarch64-linux

      - name: List flake structure
        run: nix flake show

      - name: Run build (flake)
        run: nix build '.#nixosConfigurations.default.config.system.build.isoImage'

      - run: |
          ls -lah ./result/iso/nixos.iso

      - name: Uploade iso
        uses: actions/upload-artifact@v3
        with:
          name: aarch64-iso
          path: ./result/iso/nixos.iso
